/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/slok/role-operator/pkg/apis/roleoperator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMultiRoleBindings implements MultiRoleBindingInterface
type FakeMultiRoleBindings struct {
	Fake *FakeRoleoperatorV1alpha1
	ns   string
}

var multirolebindingsResource = schema.GroupVersionResource{Group: "roleoperator.slok.xyz", Version: "v1alpha1", Resource: "multirolebindings"}

var multirolebindingsKind = schema.GroupVersionKind{Group: "roleoperator.slok.xyz", Version: "v1alpha1", Kind: "MultiRoleBinding"}

// Get takes name of the multiRoleBinding, and returns the corresponding multiRoleBinding object, and an error if there is any.
func (c *FakeMultiRoleBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.MultiRoleBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(multirolebindingsResource, c.ns, name), &v1alpha1.MultiRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiRoleBinding), err
}

// List takes label and field selectors, and returns the list of MultiRoleBindings that match those selectors.
func (c *FakeMultiRoleBindings) List(opts v1.ListOptions) (result *v1alpha1.MultiRoleBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(multirolebindingsResource, multirolebindingsKind, c.ns, opts), &v1alpha1.MultiRoleBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MultiRoleBindingList{}
	for _, item := range obj.(*v1alpha1.MultiRoleBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested multiRoleBindings.
func (c *FakeMultiRoleBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(multirolebindingsResource, c.ns, opts))

}

// Create takes the representation of a multiRoleBinding and creates it.  Returns the server's representation of the multiRoleBinding, and an error, if there is any.
func (c *FakeMultiRoleBindings) Create(multiRoleBinding *v1alpha1.MultiRoleBinding) (result *v1alpha1.MultiRoleBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(multirolebindingsResource, c.ns, multiRoleBinding), &v1alpha1.MultiRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiRoleBinding), err
}

// Update takes the representation of a multiRoleBinding and updates it. Returns the server's representation of the multiRoleBinding, and an error, if there is any.
func (c *FakeMultiRoleBindings) Update(multiRoleBinding *v1alpha1.MultiRoleBinding) (result *v1alpha1.MultiRoleBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(multirolebindingsResource, c.ns, multiRoleBinding), &v1alpha1.MultiRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiRoleBinding), err
}

// Delete takes name of the multiRoleBinding and deletes it. Returns an error if one occurs.
func (c *FakeMultiRoleBindings) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(multirolebindingsResource, c.ns, name), &v1alpha1.MultiRoleBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMultiRoleBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(multirolebindingsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.MultiRoleBindingList{})
	return err
}

// Patch applies the patch and returns the patched multiRoleBinding.
func (c *FakeMultiRoleBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MultiRoleBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(multirolebindingsResource, c.ns, name, data, subresources...), &v1alpha1.MultiRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultiRoleBinding), err
}
