/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/slok/role-operator/pkg/apis/roleoperator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePermissions implements PermissionInterface
type FakePermissions struct {
	Fake *FakeRoleoperatorV1alpha1
}

var permissionsResource = schema.GroupVersionResource{Group: "roleoperator.slok.xyz", Version: "v1alpha1", Resource: "permissions"}

var permissionsKind = schema.GroupVersionKind{Group: "roleoperator.slok.xyz", Version: "v1alpha1", Kind: "Permission"}

// Get takes name of the permission, and returns the corresponding permission object, and an error if there is any.
func (c *FakePermissions) Get(name string, options v1.GetOptions) (result *v1alpha1.Permission, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(permissionsResource, name), &v1alpha1.Permission{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Permission), err
}

// List takes label and field selectors, and returns the list of Permissions that match those selectors.
func (c *FakePermissions) List(opts v1.ListOptions) (result *v1alpha1.PermissionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(permissionsResource, permissionsKind, opts), &v1alpha1.PermissionList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PermissionList{}
	for _, item := range obj.(*v1alpha1.PermissionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested permissions.
func (c *FakePermissions) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(permissionsResource, opts))
}

// Create takes the representation of a permission and creates it.  Returns the server's representation of the permission, and an error, if there is any.
func (c *FakePermissions) Create(permission *v1alpha1.Permission) (result *v1alpha1.Permission, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(permissionsResource, permission), &v1alpha1.Permission{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Permission), err
}

// Update takes the representation of a permission and updates it. Returns the server's representation of the permission, and an error, if there is any.
func (c *FakePermissions) Update(permission *v1alpha1.Permission) (result *v1alpha1.Permission, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(permissionsResource, permission), &v1alpha1.Permission{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Permission), err
}

// Delete takes name of the permission and deletes it. Returns an error if one occurs.
func (c *FakePermissions) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(permissionsResource, name), &v1alpha1.Permission{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePermissions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(permissionsResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.PermissionList{})
	return err
}

// Patch applies the patch and returns the patched permission.
func (c *FakePermissions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Permission, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(permissionsResource, name, data, subresources...), &v1alpha1.Permission{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Permission), err
}
