/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/slok/role-operator/pkg/apis/roleoperator/v1alpha1"
	scheme "github.com/slok/role-operator/pkg/client/k8s/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PermissionsGetter has a method to return a PermissionInterface.
// A group's client should implement this interface.
type PermissionsGetter interface {
	Permissions() PermissionInterface
}

// PermissionInterface has methods to work with Permission resources.
type PermissionInterface interface {
	Create(*v1alpha1.Permission) (*v1alpha1.Permission, error)
	Update(*v1alpha1.Permission) (*v1alpha1.Permission, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Permission, error)
	List(opts v1.ListOptions) (*v1alpha1.PermissionList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Permission, err error)
	PermissionExpansion
}

// permissions implements PermissionInterface
type permissions struct {
	client rest.Interface
}

// newPermissions returns a Permissions
func newPermissions(c *RoleoperatorV1alpha1Client) *permissions {
	return &permissions{
		client: c.RESTClient(),
	}
}

// Get takes name of the permission, and returns the corresponding permission object, and an error if there is any.
func (c *permissions) Get(name string, options v1.GetOptions) (result *v1alpha1.Permission, err error) {
	result = &v1alpha1.Permission{}
	err = c.client.Get().
		Resource("permissions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Permissions that match those selectors.
func (c *permissions) List(opts v1.ListOptions) (result *v1alpha1.PermissionList, err error) {
	result = &v1alpha1.PermissionList{}
	err = c.client.Get().
		Resource("permissions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested permissions.
func (c *permissions) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("permissions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a permission and creates it.  Returns the server's representation of the permission, and an error, if there is any.
func (c *permissions) Create(permission *v1alpha1.Permission) (result *v1alpha1.Permission, err error) {
	result = &v1alpha1.Permission{}
	err = c.client.Post().
		Resource("permissions").
		Body(permission).
		Do().
		Into(result)
	return
}

// Update takes the representation of a permission and updates it. Returns the server's representation of the permission, and an error, if there is any.
func (c *permissions) Update(permission *v1alpha1.Permission) (result *v1alpha1.Permission, err error) {
	result = &v1alpha1.Permission{}
	err = c.client.Put().
		Resource("permissions").
		Name(permission.Name).
		Body(permission).
		Do().
		Into(result)
	return
}

// Delete takes name of the permission and deletes it. Returns an error if one occurs.
func (c *permissions) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("permissions").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *permissions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Resource("permissions").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched permission.
func (c *permissions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Permission, err error) {
	result = &v1alpha1.Permission{}
	err = c.client.Patch(pt).
		Resource("permissions").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
